### ISSUE TITLE
Feature request: instances for more parsing libraries

### ISSUE THREAD

**Issue by polux** [ekmett/parsers#57]
I would be nice to have instances of the classes exposed by this library for polyparse and uuparsinglib. I find these libraries much nicer to work with because `<|>` backtracks by default. Unfortunately, they don't come with a set of predefined parsers for common tasks like parsing floats, and I often fall back on parsec for this reason. If the combinators exposed by this library would work together with polyparse or uuparsing, I would never use parsec again.

**Comment by ibotty** [comment]
And there is also Earley. I guess it's different enough from the *parsecs to fit though.

**Comment by polux** [comment]
If Early would fit that would be awesome but I doubt it can: Early doesn't support context-dependent grammars but the interface of parsers allows for them.

**Comment by ekmett** [comment]
The main problem with adding more instances here is that it makes this harder and harder for folks to install out of the box and it gets harder and harder to justify folks picking up a dependency on this library to supply their own combinators, snowballing the problem as we pick up more dependencies.

I've limited instances we supply mostly to the haskell platform, because those are things that at least traditionally I could expect users to have to build anyways.

A better fix would be to get those libraries to incur a `parsers` dependency, or possibly **\*shudder\*** to suffer through adding mixin packages that supply orphan instances.

The latter route is probably the best plan to add support for things like `Earley`, `polyparse`, `uuparsing`, etc.
